#+TITLE: Org Manual
#+AUTHOR: keer
#+DATE: <2024-03-03 日>

* Introduction
** Activation
Here are suggested bindings, please modify the keys to your own liking.
#+BEGIN_SRC lisp
(global-set-key (kbd "C-c l") #'org-store-link)
(global-set-key (kbd "C-c a") #'org-agenda)
(global-set-key (kbd "C-c c") #'org-capture)
#+END_SRC

* Document Structure
** Headlines
#+BEGIN_SRC lisp
  ,* Top level headline
  ,** Second level
  ,*** Third level
     some text
  ,*** Third level
     more text
  ,* Another top level headline
#+END_SRC

** Visibility Cycling
*** Global and local cycling
+ TAB (org-cycle)
+ S-TAB (org-global-cycle)
** Motion
+ C-c C-n (org-next-visible-heading)
+ C-c C-p (org-previous-visible-heading)
+ C-c C-f (org-forward-heading-same-level)
+ C-c C-b (org-backward-heading-same-level)
+ C-c C-u (outline-up-heading)
+ C-c C-j (org-goto)
** Structure Editing
+ M-RET (org-meta-return) , Insert a new heading, item or row.
+ C-RET (org-insert-heading-respect-content),     Insert a new heading at the end of the current subtree.
+ M-S-RET (org-insert-todo-heading), Insert new TODO entry with same level as current heading.
+ C-S-RET (org-insert-todo-heading-respect-content), Insert new TODO entry with same level as current heading.
+ [[https://orgmode.org/manual/Structure-Editing.html][etc.]]
