#+TITLE: Org Manual
#+AUTHOR: keer
#+DATE: <2024-03-03 日>

* Introduction
** Activation
Here are suggested bindings, please modify the keys to your own liking.
#+BEGIN_SRC lisp
(global-set-key (kbd "C-c l") #'org-store-link)
(global-set-key (kbd "C-c a") #'org-agenda)
(global-set-key (kbd "C-c c") #'org-capture)
#+END_SRC

* Document Structure
** Headlines
#+BEGIN_SRC org
  ,* Top level headline
  ,** Second level
  ,*** Third level
     some text
  ,*** Third level
     more text
  ,* Another top level headline
#+END_SRC

** Visibility Cycling
*** Global and local cycling
+ TAB (org-cycle)
+ S-TAB (org-global-cycle)
** Motion
+ C-c C-n (org-next-visible-heading)
+ C-c C-p (org-previous-visible-heading)
+ C-c C-f (org-forward-heading-same-level)
+ C-c C-b (org-backward-heading-same-level)
+ C-c C-u (outline-up-heading)
+ C-c C-j (org-goto)
** Structure Editing
+ M-RET (org-meta-return) , Insert a new heading, item or row.
+ C-RET (org-insert-heading-respect-content),     Insert a new heading at the end of the current subtree.
+ M-S-RET (org-insert-todo-heading), Insert new TODO entry with same level as current heading.
+ C-S-RET (org-insert-todo-heading-respect-content), Insert new TODO entry with same level as current heading.
+ [[https://orgmode.org/manual/Structure-Editing.html][etc.]]
** TODO [[https://orgmode.org/manual/Sparse-Trees.html][Sparse Trees]]
** Plain Lists
Org knows ordered lists, unordered lists, and description lists.
+ Unordered list items start with =-=, =+=, or =*= as bullets.
+ Ordered list items start with a numeral followed by either a period or a right parenthesis, such as =1.= or =1)=.
+ [-]  TODO Description list items are unordered list items, and contain the separator ‘::’ to distinguish the
  description term from the description.

A list ends whenever every item has ended, which means before any line less or equally indented than items at top level.
It also ends before two blank lines. In that case, all items are closed. Here is an example:
#+BEGIN_SRC org
  * Lord of the Rings
  My favorite scenes are (in this order)
  1. The attack of the Rohirrim
  2. Eowyn's fight with the witch king
     + this was already my favorite scene in the book
     + I really like Miranda Otto.
  3. Peter Jackson being shot by Legolas
     - on DVD only
     He makes a really funny face when it happens.
  But in the end, no individual scenes matter but the film as a whole.
  Important actors in this film are:
  - Elijah Wood :: He plays Frodo
  - Sean Astin :: He plays Sam, Frodo's friend.  I still remember him
       very well from his role as Mikey Walsh in /The Goonies/.

     #+END_SRC
** Drawers
** Blocks
* Tables
** Build-in Table Editor

A table might look like this:

| Name  | Phone | Age |
|-------+-------+-----|
| Peter |  1234 |  17 |
| Anna  |  4321 |   9 |


To create the above table, you would only type
#+BEGIN_SRC
| Name | Phone | Age |
|-
#+END_SRC

and then press ~TAB~ to align the table and start filling in fields.

Event faster would be to type ~|Name|Phone|Age~ followed by ~C-c RET~.








** Column Width and Alignment
